export const GET_PRESENT_PATIENT = 'GET_PRESENT_PATIENT';
export const GET_QUITING_PATIENT = 'GET_QUITING_PATIENT';
export const GET_ADDITIONAL_PRESENT = 'GET_ADDITIONAL_PRESENT';
export const GET_ADDITIONAL_QUITTING = 'GET_ADDITIONAL_QUITTING';
export const SET_PRESENT_PATIENT = 'SET_PRESENT_PATIENT';
export const SET_QUITTING_PATIENT = 'SET_QUITTING_PATIENT';
